name: "Install Dependencies"
inputs:
  torch-version:
    description: torch version to install
  torchvision-version:
    description: torch vision version to install, version number or "master"
  pytorch-index:
    description: where to install torch from
    required: false
    default: "https://download.pytorch.org/whl/torch_stable.html"
    # use test wheels index to have access to RC wheels
    # https://download.pytorch.org/whl/test/torch_test.html
runs:
  using: composite
  steps:
  - name: Install Dependencies
    shell: bash
    run: |
      # disable crash coredump, so unittests fail fast
      sudo systemctl stop apport.service || true
    - name: Install dependencies
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
        PYTORCH_VERSION: ${{ inputs.pytorch-version }}
        CUDA_VERSION: ${{ inputs.cuda-version }}
        COMMENT_BODY: ${{ inputs.comment-body }}
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y ninja-build

        # install a newer version of cmake
        if [[ "$PYTHON_VERSION" == 3.6 ]]; then
          pip install "cmake>=3.19"
        fi

        # install pytorch
        if [[ "$CUDA_VERSION" == "cpu" ]]; then
          pip install torch=="${PYTORCH_VERSION}"+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
        else
          pip install torch=="${PYTORCH_VERSION}" torchvision==0.11.1 --extra-index-url https://download.pytorch.org/whl/cu"${CUDA_VERSION}"
        fi

        # install other dependencies
        pip install -r requirements.txt
        if [[ "$COMMENT_BODY" == *"/rebuild-windows"* ]]; then
          pip install git+https://github.com/facebookresearch/fvcore
        fi
